# 1. Passo a passo para Implementar Bagging

1. Baixar base de dados
2. Criar as amostras com reposição e colocá-las em uma lista.
3. Para cada amostra, dividir em treino e teste
4. Para cada amostra, treinar o modelo
5. Para cada amostra, criar previsões de teste.
6. Juntar todas as previsões em um dataframe.
7. Fazer a agregação a partir das frequências

# 2. Descrição

O Bagging é um processo de combinação de modelos para melhorar a eficácia dos resultados. Ele consiste em criar amostras variadas com repetição a partir do conjunto de dados inicial. Cada amostra é usada para treinar um modelo, e cada modelo é utilizado para fazer previsões. A partir dessas previsões, uma técnica de agregação é aplicada para determinar o melhor resultado. No caso de variáveis discretas, o melhor resultado é aquele com maior frequência entre os diferentes modelos. Para variáveis contínuas, o melhor resultado é a média de todos os resultados.

# 3. Exemplo de processo de bagging

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df = sns.load_dataset("penguins")
df.dropna(inplace=True)
df['species'] = df['species'].map({'Adelie': 0, 'Chinstrap':1, 'Gentoo': 2 })
df['sex'] = df['sex'].map({'Male':0, 'Female':1})
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Torgersen,39.1,18.7,181.0,3750.0,0
1,0,Torgersen,39.5,17.4,186.0,3800.0,1
2,0,Torgersen,40.3,18.0,195.0,3250.0,1
4,0,Torgersen,36.7,19.3,193.0,3450.0,1
5,0,Torgersen,39.3,20.6,190.0,3650.0,0
...,...,...,...,...,...,...,...
338,2,Biscoe,47.2,13.7,214.0,4925.0,1
340,2,Biscoe,46.8,14.3,215.0,4850.0,1
341,2,Biscoe,50.4,15.7,222.0,5750.0,0
342,2,Biscoe,45.2,14.8,212.0,5200.0,1
343,2,Biscoe,49.9,16.1,213.0,5400.0,0

In [ ]:
amostras = []
for i in range(20):
    amostras.append(df.sample(len(df), replace=True, random_state=i))

amostras

[     species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 178        1      Dream            50.5           18.4              200.0
 53         0     Biscoe            42.0           19.5              200.0
 123        0  Torgersen            41.4           18.5              202.0
 198        1      Dream            50.1           17.9              190.0
 332        2     Biscoe            43.5           15.2              213.0
 ..       ...        ...             ...            ...                ...
 233        2     Biscoe            48.4           14.6              213.0
 281        2     Biscoe            46.2           14.9              221.0
 298        2     Biscoe            45.2           13.8              215.0
 57         0     Biscoe            40.6           18.8              193.0
 164        1      Dream            47.0           17.3              185.0

      body_mass_g  sex
 178       3400.0    1
 53        4050.0    0
 123       3875.0    0
 198       3400.0    1
 332       4650.0    1
 ..           ...  ...
 233       5850.0    0
 281       5300.0    0
 298       4750.0    1
 57        3800.0    0
 164       3700.0    1

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 42         0      Dream            36.0           18.5              186.0
 241        2     Biscoe            45.1           14.5              215.0
 78         0  Torgersen            36.2           16.1              187.0
 262        2     Biscoe            45.3           13.7              210.0
 209        1      Dream            49.3           19.9              203.0
 ..       ...        ...             ...            ...                ...
 118        0  Torgersen            35.7           17.0              189.0
 150        0      Dream            36.0           17.1              187.0
 164        1      Dream            47.0           17.3              185.0
 121        0  Torgersen            37.7           19.8              198.0
 112        0     Biscoe            39.7           17.7              193.0

      body_mass_g  sex
 42        3100.0    1
 241       5000.0    1
 78        3550.0    1
 262       4300.0    1
 209       4050.0    0
 ..           ...  ...
 118       3350.0    1
 150       3700.0    1
 164       3700.0    1
 121       3500.0    0
 112       3200.0    1

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 174        1      Dream            43.2           16.6              187.0
 20         0     Biscoe            37.8           18.3              174.0
 78         0  Torgersen            36.2           16.1              187.0
 27         0     Biscoe            40.5           17.9              187.0
 307        2     Biscoe            51.3           14.2              218.0
 ..       ...        ...             ...            ...                ...
 285        2     Biscoe            49.8           16.8              230.0
 263        2     Biscoe            49.6           15.0              216.0
 160        1      Dream            46.0           18.9              195.0
 333        2     Biscoe            51.5           16.3              230.0
 185        1      Dream            51.0           18.8              203.0

      body_mass_g  sex
 174       2900.0    1
 20        3400.0    1
 78        3550.0    1
 27        3200.0    1
 307       5300.0    0
 ..           ...  ...
 285       5700.0    0
 263       4750.0    0
 160       4150.0    1
 333       5500.0    0
 185       4100.0    0

 [333 rows x 7 columns],
      species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 158        1   Dream            46.1           18.2              178.0
 256        2  Biscoe            42.6           13.7              213.0
 137        0   Dream            40.2           20.1              200.0
 263        2  Biscoe            49.6           15.0              216.0
 284        2  Biscoe            45.8           14.2              219.0
 ..       ...     ...             ...            ...                ...
 327        2  Biscoe            53.4           15.8              219.0
 160        1   Dream            46.0           18.9              195.0
 247        2  Biscoe            47.8           15.0              215.0
 229        2  Biscoe            46.8           15.4              215.0
 134        0   Dream            38.1           17.6              187.0

      body_mass_g  sex
 158       3250.0    1
 256       4950.0    1
 137       3975.0    0
 263       4750.0    0
 284       4700.0    1
 ..           ...  ...
 327       5500.0    0
 160       4150.0    1
 247       5650.0    0
 229       5150.0    0
 134       3425.0    1

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 128        0  Torgersen            39.0           17.1              191.0
 180        1      Dream            46.4           17.8              191.0
 203        1      Dream            51.4           19.0              201.0
 93         0      Dream            39.6           18.1              186.0
 314        2     Biscoe            44.5           14.7              214.0
 ..       ...        ...             ...            ...                ...
 227        2     Biscoe            46.7           15.3              219.0
 44         0      Dream            37.0           16.9              185.0
 279        2     Biscoe            50.4           15.3              224.0
 56         0     Biscoe            39.0           17.5              186.0
 33         0      Dream            40.9           18.9              184.0

      body_mass_g  sex
 128       3050.0    1
 180       3700.0    1
 203       3950.0    0
 93        4450.0    0
 314       4850.0    1
 ..           ...  ...
 227       5200.0    0
 44        3000.0    1
 279       5550.0    0
 56        3550.0    1
 33        3900.0    0

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 212        1      Dream            51.9           19.5              206.0
 195        1      Dream            45.5           17.0              196.0
 124        0  Torgersen            35.2           15.9              186.0
 79         0  Torgersen            42.1           19.1              195.0
 13         0  Torgersen            38.6           21.2              191.0
 ..       ...        ...             ...            ...                ...
 243        2     Biscoe            46.3           15.8              215.0
 7          0  Torgersen            39.2           19.6              195.0
 179        1      Dream            49.5           19.0              200.0
 64         0     Biscoe            36.4           17.1              184.0
 327        2     Biscoe            53.4           15.8              219.0

      body_mass_g  sex
 212       3950.0    0
 195       3500.0    1
 124       3050.0    1
 79        4000.0    0
 13        3800.0    0
 ..           ...  ...
 243       5050.0    0
 7         4675.0    0
 179       3800.0    0
 64        2850.0    1
 327       5500.0    0

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 207        1      Dream            52.2           18.8              197.0
 233        2     Biscoe            48.4           14.6              213.0
 112        0     Biscoe            39.7           17.7              193.0
 327        2     Biscoe            53.4           15.8              219.0
 289        2     Biscoe            50.7           15.0              223.0
 ..       ...        ...             ...            ...                ...
 69         0  Torgersen            41.8           19.4              198.0
 165        1      Dream            52.0           18.1              201.0
 224        2     Biscoe            47.6           14.5              215.0
 236        2     Biscoe            42.0           13.5              210.0
 221        2     Biscoe            50.0           16.3              230.0

      body_mass_g  sex
 207       3450.0    0
 233       5850.0    0
 112       3200.0    1
 327       5500.0    0
 289       5550.0    0
 ..           ...  ...
 69        4450.0    0
 165       4050.0    0
 224       5400.0    0
 236       4150.0    1
 221       5700.0    0

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 181        1      Dream            52.8           20.0              205.0
 202        1      Dream            48.1           16.4              199.0
 30         0      Dream            39.5           16.7              178.0
 73         0  Torgersen            45.8           18.9              197.0
 217        1      Dream            49.6           18.2              193.0
 ..       ...        ...             ...            ...                ...
 33         0      Dream            40.9           18.9              184.0
 187        1      Dream            47.5           16.8              199.0
 85         0      Dream            41.3           20.3              194.0
 108        0     Biscoe            38.1           17.0              181.0
 340        2     Biscoe            46.8           14.3              215.0

      body_mass_g  sex
 181       4550.0    0
 202       3325.0    1
 30        3250.0    1
 73        4150.0    0
 217       3775.0    0
 ..           ...  ...
 33        3900.0    0
 187       3900.0    1
 85        3550.0    0
 108       3175.0    1
 340       4850.0    1

 [333 rows x 7 columns],
      species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 139        0   Dream            39.7           17.9              193.0
 142        0   Dream            32.1           15.5              188.0
 197        1   Dream            50.8           18.5              201.0
 54         0  Biscoe            34.5           18.1              187.0
 91         0   Dream            41.1           18.1              205.0
 ..       ...     ...             ...            ...                ...
 303        2  Biscoe            50.0           15.9              224.0
 299        2  Biscoe            45.2           16.4              223.0
 228        2  Biscoe            43.3           13.4              209.0
 172        1   Dream            42.4           17.3              181.0
 298        2  Biscoe            45.2           13.8              215.0

      body_mass_g  sex
 139       4250.0    0
 142       3050.0    1
 197       4450.0    0
 54        2900.0    1
 91        4300.0    0
 ..           ...  ...
 303       5350.0    0
 299       5950.0    0
 228       4400.0    1
 172       3600.0    1
 298       4750.0    1

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 132        0      Dream            36.8           18.5              193.0
 62         0     Biscoe            37.6           17.0              185.0
 258        2     Biscoe            44.0           13.6              208.0
 131        0  Torgersen            43.1           19.2              197.0
 71         0  Torgersen            39.7           18.4              190.0
 ..       ...        ...             ...            ...                ...
 55         0     Biscoe            41.4           18.6              191.0
 341        2     Biscoe            50.4           15.7              222.0
 290        2     Biscoe            47.7           15.0              216.0
 242        2     Biscoe            46.5           14.5              213.0
 155        1      Dream            45.4           18.7              188.0

      body_mass_g  sex
 132       3500.0    1
 62        3600.0    1
 258       4350.0    1
 131       3500.0    0
 71        3900.0    0
 ..           ...  ...
 55        3700.0    0
 341       5750.0    0
 290       4750.0    1
 242       4400.0    1
 155       3525.0    1

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 272        2     Biscoe            45.1           14.4              210.0
 131        0  Torgersen            43.1           19.2              197.0
 20         0     Biscoe            37.8           18.3              174.0
 329        2     Biscoe            48.1           15.1              209.0
 129        0  Torgersen            44.1           18.0              210.0
 ..       ...        ...             ...            ...                ...
 55         0     Biscoe            41.4           18.6              191.0
 136        0      Dream            35.6           17.5              191.0
 335        2     Biscoe            55.1           16.0              230.0
 231        2     Biscoe            49.0           16.1              216.0
 34         0      Dream            36.4           17.0              195.0

      body_mass_g  sex
 272       4400.0    1
 131       3500.0    0
 20        3400.0    1
 329       5500.0    0
 129       4000.0    0
 ..           ...  ...
 55        3700.0    0
 136       3175.0    1
 335       5850.0    0
 231       5550.0    0
 34        3325.0    1

 [333 rows x 7 columns],
      species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 197        1   Dream            50.8           18.5              201.0
 86         0   Dream            36.3           19.5              190.0
 97         0   Dream            40.3           18.5              196.0
 276        2  Biscoe            43.8           13.9              208.0
 343        2  Biscoe            49.9           16.1              213.0
 ..       ...     ...             ...            ...                ...
 219        1   Dream            50.2           18.7              198.0
 244        2  Biscoe            42.9           13.1              215.0
 248        2  Biscoe            48.2           14.3              210.0
 215        1   Dream            55.8           19.8              207.0
 244        2  Biscoe            42.9           13.1              215.0

      body_mass_g  sex
 197       4450.0    0
 86        3800.0    0
 97        4350.0    0
 276       4300.0    1
 343       5400.0    0
 ..           ...  ...
 219       3775.0    1
 244       5000.0    1
 248       4600.0    1
 215       4000.0    0
 244       5000.0    1

 [333 rows x 7 columns],
      species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 342        2  Biscoe            45.2           14.8              212.0
 161        1   Dream            51.3           19.9              198.0
 260        2  Biscoe            42.7           13.7              208.0
 248        2  Biscoe            48.2           14.3              210.0
 136        0   Dream            35.6           17.5              191.0
 ..       ...     ...             ...            ...                ...
 113        0  Biscoe            42.2           19.5              197.0
 23         0  Biscoe            38.2           18.1              185.0
 165        1   Dream            52.0           18.1              201.0
 212        1   Dream            51.9           19.5              206.0
 186        1   Dream            49.7           18.6              195.0

      body_mass_g  sex
 342       5200.0    1
 161       3700.0    0
 260       3950.0    1
 248       4600.0    1
 136       3175.0    1
 ..           ...  ...
 113       4275.0    0
 23        3950.0    0
 165       4050.0    0
 212       3950.0    0
 186       3600.0    0

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 182        1      Dream            40.9           16.6              187.0
 80         0  Torgersen            34.6           17.2              189.0
 21         0     Biscoe            37.7           18.7              180.0
 236        2     Biscoe            42.0           13.5              210.0
 251        2     Biscoe            42.8           14.2              209.0
 ..       ...        ...             ...            ...                ...
 250        2     Biscoe            47.3           15.3              222.0
 319        2     Biscoe            51.1           16.5              225.0
 301        2     Biscoe            52.5           15.6              221.0
 186        1      Dream            49.7           18.6              195.0
 151        0      Dream            41.5           18.5              201.0

      body_mass_g  sex
 182       3200.0    1
 80        3200.0    1
 21        3600.0    0
 236       4150.0    1
 251       4700.0    1
 ..           ...  ...
 250       5250.0    0
 319       5250.0    0
 301       5450.0    0
 186       3600.0    0
 151       4000.0    0

 [333 rows x 7 columns],
      species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 113        0  Biscoe            42.2           19.5              197.0
 275        2  Biscoe            45.0           15.4              220.0
 337        2  Biscoe            48.8           16.2              222.0
 256        2  Biscoe            42.6           13.7              213.0
 240        2  Biscoe            50.2           14.3              218.0
 ..       ...     ...             ...            ...                ...
 85         0   Dream            41.3           20.3              194.0
 67         0  Biscoe            41.1           19.1              188.0
 142        0   Dream            32.1           15.5              188.0
 303        2  Biscoe            50.0           15.9              224.0
 279        2  Biscoe            50.4           15.3              224.0

      body_mass_g  sex
 113       4275.0    0
 275       5050.0    0
 337       6000.0    0
 256       4950.0    1
 240       5700.0    0
 ..           ...  ...
 85        3550.0    0
 67        4100.0    0
 142       3050.0    1
 303       5350.0    0
 279       5550.0    0

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 252        2     Biscoe            45.1           14.5              207.0
 139        0      Dream            39.7           17.9              193.0
 162        1      Dream            46.6           17.8              193.0
 161        1      Dream            51.3           19.9              198.0
 205        1      Dream            50.7           19.7              203.0
 ..       ...        ...             ...            ...                ...
 7          0  Torgersen            39.2           19.6              195.0
 256        2     Biscoe            42.6           13.7              213.0
 259        2     Biscoe            48.7           15.7              208.0
 55         0     Biscoe            41.4           18.6              191.0
 231        2     Biscoe            49.0           16.1              216.0

      body_mass_g  sex
 252       5050.0    1
 139       4250.0    0
 162       3800.0    1
 161       3700.0    0
 205       4050.0    0
 ..           ...  ...
 7         4675.0    0
 256       4950.0    1
 259       5350.0    0
 55        3700.0    0
 231       5550.0    0

 [333 rows x 7 columns],
      species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 175        1      Dream            50.6           19.4              193.0
 244        2     Biscoe            42.9           13.1              215.0
 127        0  Torgersen            41.5           18.3              195.0
 75         0  Torgersen            42.8           18.5              195.0
 330        2     Biscoe            50.5           15.2              216.0
 ..       ...        ...             ...            ...                ...
 96         0      Dream            38.1           18.6              190.0
 173        1      Dream            48.5           17.5              191.0
 68         0  Torgersen            35.9           16.6              190.0
 36         0      Dream            38.8           20.0              190.0

In [ ]:
splits = []
for amostra in amostras:
    #print(amostra['island'])
    X = amostra.drop(['species', 'island'], axis=1)
    y = amostra['species']
    splits.append(train_test_split(X, y, test_size=0.3))

splits[0]

[     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex
 308            47.5           14.0              212.0       4875.0    1
 101            41.0           20.0              203.0       4725.0    0
 30             39.5           16.7              178.0       3250.0    1
 180            46.4           17.8              191.0       3700.0    1
 117            37.3           20.5              199.0       3775.0    0
 ..              ...            ...                ...          ...  ...
 295            48.6           16.0              230.0       5800.0    0
 213            46.8           16.5              189.0       3650.0    1
 250            47.3           15.3              222.0       5250.0    0
 205            50.7           19.7              203.0       4050.0    0
 182            40.9           16.6              187.0       3200.0    1

 [233 rows x 5 columns],
      bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex
 299            45.2           16.4              223.0       5950.0    0
 178            50.5           18.4              200.0       3400.0    1
 78             36.2           16.1              187.0       3550.0    1
 123            41.4           18.5              202.0       3875.0    0
 299            45.2           16.4              223.0       5950.0    0
 ..              ...            ...                ...          ...  ...
 37             42.2           18.5              180.0       3550.0    1
 233            48.4           14.6              213.0       5850.0    0
 16             38.7           19.0              195.0       3450.0    1
 264            50.5           15.9              222.0       5550.0    0
 101            41.0           20.0              203.0       4725.0    0

 [100 rows x 5 columns],
 308    2
 101    0
 30     0
 180    1
 117    0
       ..
 295    2
 213    1
 250    2
 205    1
 182    1
 Name: species, Length: 233, dtype: int64,
 299    2
 178    1
 78     0
 123    0
 299    2
       ..
 37     0
 233    2
 16     0
 264    2
 101    0
 Name: species, Length: 100, dtype: int64]

In [ ]:
models=[]

for split in splits:
    model = DecisionTreeClassifier(max_depth=5, min_samples_leaf=20)
    model.fit(split[0], split[2])
    models.append(model)

models

[DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20),
 DecisionTreeClassifier(max_depth=5, min_samples_leaf=20)]

In [ ]:
test_X= splits[0][1].sample(1, random_state=241)
test_X

     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex
126            38.8           17.6              191.0       3275.0    1

In [ ]:
predictions = []
for model in models:
    y_pred = model.predict(test_X)
    predictions.append(y_pred[0])
predictions

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
final_prediction = pd.DataFrame(predictions).value_counts().idxmax()[0]
final_prediction

0